newren/git-filter-repo

- Makefile
- documentation fixes
- fix for paths with spaces
- python shebang fix, which you may not want, and might just be an issue with my own installation (I can only use "#!/usr/bin/env python", not "python3")
Side-note:
here's what ended up working for me to install on Windows:
git clone -c core.symlinks=true https://github.com/newren/git-filter-repo.git
make prefix="C:\Program Files\Git\mingw64" pythondir="C:\Python38\Lib\site-packages" mandir="C:\gnuwin32\share\man" install
- The git path I believe is standard for a Git for Windows install
- Python path is from a fresh chocolatey install
- gnuwin32: not sure if it was installed by Git for Windows, or by me from earlier...
> Installation fixes (some may be Windows-specific, some not)

- .gitignore
- git-filter-repo
- t/t9390-filter-repo.sh
- t/t9390/sample-mailmap
- t/t9390/unusual
- t/t9390/unusual-mailmap
This PR adds a `.gitignore` file and fixes two bugs.
1. The mailmap format parsed by the `git shortlog` command allows for matching mailmap entries with no email address. This is admittedly an edge case, because most Git commits will have an email address associated with them as well as a name, but technically the address isn't required, and `git shortlog` accommodates that in its mailmap format. This PR teaches `git-filter-repo` to do the same thing, fixing what was arguably a bug (or at least a missing feature) in `git-filter-repo`.
2. I ran into this bug by accident while I was investigating the previous one. Prior to the changes made in this PR, `git-filter-repo` could only be used with either the `--dry-run` flag or the `--debug` flag, not both. When run in debug mode, …
> Fix translation of mailmap entries with no email address

- release/setup.py
Multiple runs of setuptools encounter a FileExistsError exception
trying to re-symlink the same files.
This exception is safe to ignore: the files were already symlinked
so the call can be considered successful.
Signed-off-by: Sirio Balmelli <sirio@b-ad.ch>
> setup.py: test for FileExistsError on symlink

- contrib/filter-repo-demos/filter-lamely
First of all, thanks for providing this great tool for repository cleanup!
I am currently working on cleaning up line endings in a repository and couldn't find a direct way to do this (using git's automatic conversion with `.gitattributes`) other than `filter-branch` and a tree filter.
To speed the process up, I used `filter-lamely`, as I was not able to use `filter-repo` directly for this.
When checking the result, however, I noticed problems with files with special characters in their name.
After running `filter-lamely` with a tree filter, they were moved to subdirectories that begin with a `"` character.
It turns out that `filter-lamely` does not process such filenames correctly, so I fixed it.
I hope this fix is small enough to be acceptable as a GitHub PR.
```
filter-lamely does not …
```
> contrib: fix special character handling in filter-lamely

- Documentation/git-filter-repo.txt
Useful commit and reference mappings are created on every run. These are
helpful in a number of situations, and should be documented so that
end-users and Git hosts can understand how to use the output.
The commit-map is particularly useful for Git hosts to override
retention mechanisms, like hidden refs. This allows end-users can purge
large files or sensitive data.
Follow up to #98
> git-filter-repo.txt: document mapping output

- contrib/filter-repo-demos/filter-lamely
I have succesfully used `git-filter-repo` for cleanup after migrating a lot of repos from SVN to Git and subsequent consolidation of many small repos into bigger combined repos. Thanks again for maintaining this useful tool!
I even promise I did most of that work using proper `git-filter-repo` commands! However, I recently had to reach for `filter-lamely` again for line ending conversion and noticed that it breaks when the repo has annotated tags because of a missing module prefix. This PR should fix that.
> filter-lamely: fix NameError because of forgotten fr module prefix

- .gitattributes
- .github/workflows/test.yml
- .gitignore
- t/t9390-filter-repo.sh
- t/t9391-filter-repo-lib-usage.sh
The idea is to fix the tests so that they pass on Windows, and then have a GitHub workflow that runs on every push and Pull Request to ensure that no regressions are introduced on the main three platforms: Windows, macOS and Linux.
> Add a GitHub workflow for continuous testing

- git-filter-repo
When `git filter-repo --path-rename foo` is given, and `foo` does not have a colon, an exception with the following stack trace crashes the program.
```
File "/usr/local/bin/git-filter-repo", line 1626, in __call__
if values[0] and values[1] and not (
IndexError: list index out of range
```
This commit fixes the bug, and also checks against the user giving more than one colon in the argument (that would probably indicate some kind of mistake).
> Fix bug in --path-rename argument without colon

- .github/workflows/test.yml
- Makefile
- t/run_coverage
- t/run_tests
There are currently 2 test runners: github workflows, and `t/run_coverage`. The github one isn't useful outside of github workflows, and run_coverage doesn't usefully report failures, and mandates running coverage reports.
This combines both into one, `t/run_tests`, that `t/run_coverage` and the github workflows can both use. They all should now exit non-zero if a test fails.
> Re-useable test-runner script

- Documentation/git-filter-repo.txt
The "Filtering based on many paths" section includes this code snippet,
```
regex:^.*/.*/[0-9]{4}-[0-9]{2}-[0-9]{2}.txt$
```
and this  text, 
> files whose name was of the form YYYY.MM-DD.txt at least two subdirectories deep
Update the text to YYYY-MM-DD.txt to match the regex in the code snippet.
> git-filter-repo.txt: fix typo in paths-from-file example

- t/t9390/less-empty-keepme
- t/t9390/more-empty-keepme
Commit order from `fast-export --first-parent` has changed in git 2.35, see https://github.com/git/git/commit/726a228dfb19fae8befa0f209436f8fae7919a58
This will break the same tests on older git releases. I can't see an easy mechanism to skip these tests on older versions or carry multiple expected test outputs.
Fixes: #344
> Update expected test data for git 2.35

- Makefile
Packaging `git-filter-repo` is a challenge, as the Makefile install target is mostly geared toward installing it on the local system. One reason is because the Makefile does not support `DESTDIR`. Another reason is that because it uses `cp`, all parent directories must already exist.
This pull request addresses both these issues.
> Makefile: add support for DESTDIR

- contrib/filter-repo-demos/clean-ignore
This allows the user to provide further argument parameters to `git-filter-repo` when running `clean-ignore`. A common example of when this is needed is when running `clean-ignore` on a repo not freshly cloned, causing below error. 
```
Aborting: Refusing to destructively overwrite repo history since
this does not look like a fresh clone.
```
Furthermore, I add the `git-clean-ignore` naming to allow git's auto-detection of the dash name to integrate it as sub-command automatically. 
With these change, it is possible to call as follows:
```shell
git clean-ignore --force
```
> allow git-filter-repo clean-ignore args forwarding

- contrib/filter-repo-demos/lint-history
Unfortunately, `lint-history` is missing most standard arguments of `git-filter-repo`. I was particularly missing `--refs` to limit history rewrite to a subset of commits. This simple change here solved that issue for me.
However, probably there is a better way to provide standard arguments in `lint-history` as well. Please feel free to adapt this PR accordingly.
> lint-history: add --refs argument

- Makefile
> Makefile: abstract out the `install` binary used

- README.md
While I am not a big fan of PRs to to fix typos, the README.md `Design Rationale` section has a small typo ("any" instead of "each") that confused me on my first read-through so I added a tiny PR to fix it, since it hinders understanding.
I am assuming that the design rationale was that there were no existing tools which implemented all of the first 8 traits, and none that implemented even a single one of the final four traits. This change just makes that clear (if that was the intended interpretation!).
> README: fix typo to clarify design rationale

- .github/dependabot.yml
Some of the github actions used within this project are somewhat out dated. For example, the latest version of checkout is currently on v4, but this project is still using v2. This change will make use of dependabot to submit pull requests every month of updates of any of the github actions this project uses if there are newer versions released.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
> Update gha using dependabot monthly

- git-filter-repo
Callbacks currently inherit the global scope from the library, which leaks private API details. This change limits the globals visible to callbacks to just the public library API and its imports (so using, e.g., `re` continues to work without import).
This is technically a breaking change, if anyone relies on these extra globals, but this change seems well within the API guarantees.
The only question is how much should be made visible? Several of these imports have questionable utility for callbacks, so might make sense to prune from the list. What about Python `__`-globals? Some of those might be necessary, and they could be forwarded or stubbed.
I've included a diff of the globals and locals for your review:
```diff
Callback globals:
{
-  'Alias': <class '__main__.Alias'>,
- …
```
> Cleanup callback scope

- git-filter-repo
Feature to skip `git gc` run, useful for multiple `git-filter-repo` runs.
> Add --no-gc option

- INSTALL.md
From the issues and `INSTALL.md` one gets the impression that installation on windows is troublesome. However, the package can be simply installed with [pipx](https://pypa.github.io/pipx/) on Windows. Since pipx is a solid widely used tool mentioning this option could help.
> Mention pypi / pipx as simple installation option

- t/t9394-filter-repo-sanity-checks-and-bigger-repo-setup.sh
Instead of trying to expect a static difference of the compressed content between zlib and zlib-ng mask the compressed size and ignore it while comparing.
Fixes: #614
> t9394: Mask compressed size for comparison.

- git-filter-repo
Fixes the issue reported in #640.
This print-out message is missing a terminating line-break,
and gets partially overwritten by other text:
Warning: Removing recursively: <filename>
Example output:
Processed 28217 blob sizesely: ".git\filter-repo\analysis"
(Notice how the words "sizes" and "recursively" get combined,
into "sizesely" on the first line.)
Adding the missing newline corrects the output:
Warning: Removing recursively: ".git\filter-repo\analysis"
Processed 28217 blob sizes
> Add missing newline in printout
